import streamlit as st

st.set_page_config(page_title="About - River Dipstick", page_icon="static/logo.png")

st.write("This app is designed to answer the eternal question...")
st.markdown("*Will the river be good for fly fishing tomorrow?*")
st.write("The features described below are experimental but will improve over time as more data is collected.")
st.subheader("Colour Coding")
st.write("The colours in each river table indicate if the conditions are good for fly fishing near that measurement station at the current time")
st.markdown(':red[Bad levels, stay at home]')
st.markdown(':yellow[It might be worth a cast]')
st.markdown(':green[Pull a sicky and go fishing!!]')
st.write("Colour coding is only added to beats I know about, crowd-sourcing will come next")
st.subheader("Predicted Levels")
st.write("Machine Learning (ML) is used to predict the river level in 24 hours.")
st.write("The current model uses at least 1 years worth of Level and Rainfall data to make a prediction for each measurement station")
st.write("To see the ML predictions, toggle 'Predictions' on the Dashboard.")
st.markdown(':blue[The blue line is real data from the Environment Agency]')
st.markdown(':grey[The grey line shows how the prediction model performed over the previous 7 days]')
st.markdown(':violet[Violet is the 24 hr river level prediction]')
st.subheader("Rainfall")
st.write("Toggle 'Rain' to view how much rain has fallen near the measurement over the last 7 days.")
st.subheader("etc")
st.write("Future plans: improved ML, more rivers and more fishing.")
st.write("Data source: [Environment Agency API](https://environment.data.gov.uk/flood-monitoring/doc/reference)")
st.write("Built using [streamlit.io](https://streamlit.io) & vibe coded by tim & grok.")